name: Ubuntu 20.04

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  coreJupyter:

    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["2.7.18", "3.6.9", "3.8.3", "3.10", "3.11"]
        sympy-version: ["sympy", "sympy==1.2"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install needed ubuntu packages
      run: |
        # use apt-spy2 to select closest apt mirror,
        # which helps avoid connectivity issues in Azure;
        # see https://github.com/actions/virtual-environments/issues/675
        sudo gem install apt-spy2
        sudo apt-spy2 fix --commit --launchpad --country=US
        # after selecting a specific mirror, we need to run 'apt-get update'
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base colordiff pandoc ffmpeg
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install --upgrade nbconvert
        python -m pip install testfixtures ${{ matrix.sympy-version }} mpmath jupyter matplotlib scipy nrpylatex
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Core Jupyter notebook testsuite
      run: |
        ./UnitTesting/core_Jupyter_notebook_testsuite.sh

  coreJupdevSymPy:

    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8.3", "3.10", "3.11"]  # dev SymPy requires Python 3.8+

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install needed ubuntu packages
      run: |
        # use apt-spy2 to select closest apt mirror,
        # which helps avoid connectivity issues in Azure;
        # see https://github.com/actions/virtual-environments/issues/675
        sudo gem install apt-spy2
        sudo apt-spy2 fix --commit --launchpad --country=US
        # after selecting a specific mirror, we need to run 'apt-get update'
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base colordiff pandoc ffmpeg
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install --upgrade nbconvert
        python -m pip install --upgrade git+https://github.com/sympy/sympy/
        python -m pip install testfixtures mpmath jupyter matplotlib scipy nrpylatex
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Core Jupyter notebook testsuite
      run: |
        ./UnitTesting/core_Jupyter_notebook_testsuite.sh


  UnitTests:

    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["2.7.18", "3.6.9", "3.8.3", "3.10", "3.11"]
        sympy-version: ["sympy", "sympy==1.3"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install needed ubuntu packages
      run: |
        # use apt-spy2 to select closest apt mirror,
        # which helps avoid connectivity issues in Azure;
        # see https://github.com/actions/virtual-environments/issues/675
        sudo gem install apt-spy2
        sudo apt-spy2 fix --commit --launchpad --country=US
        # after selecting a specific mirror, we need to run 'apt-get update'
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base colordiff pandoc ffmpeg
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install --upgrade nbconvert
        python -m pip install testfixtures ${{ matrix.sympy-version }} mpmath jupyter matplotlib scipy nrpylatex
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: UnitTests
      run: |
        ./UnitTesting/run_NRPy_UnitTests.sh python
