name: Ubuntu 22.04

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  coreJupdevSymPy:

    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8.12", "3.10", "3.11"]  # 3.8+ required: https://pypi.org/project/sympy/

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install needed ubuntu packages
      run: sudo apt-get update && sudo apt-get install -y texlive-latex-base colordiff pandoc ffmpeg
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install --upgrade nbconvert
        python -m pip install --upgrade git+https://github.com/sympy/sympy/
        python -m pip install testfixtures mpmath jupyter matplotlib scipy nrpylatex
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Core Jupyter notebook testsuite
      run: |
        ./UnitTesting/core_Jupyter_notebook_testsuite.sh

  CoreJuplatestSymPy:

    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7.13", "3.8.12", "3.10", "3.11"]  # Earliest version available on 22.04 = 3.7.13

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install needed ubuntu packages
      run: sudo apt-get install -y texlive-latex-base colordiff pandoc ffmpeg
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install --upgrade nbconvert
        python -m pip install testfixtures sympy mpmath jupyter matplotlib scipy nrpylatex
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Core Jupyter notebook testsuite
      run: |
        ./UnitTesting/core_Jupyter_notebook_testsuite.sh

  NRPyGiRaFFEJupdevSymPy:

    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8.12", "3.10", "3.11"]  # 3.8+ required: https://pypi.org/project/sympy/

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install needed ubuntu packages
      run: sudo apt-get install -y texlive-latex-base colordiff pandoc ffmpeg
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install --upgrade nbconvert
        python -m pip install --upgrade git+https://github.com/sympy/sympy/
        python -m pip install testfixtures mpmath jupyter matplotlib scipy nrpylatex
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Core Jupyter notebook testsuite
      run: |
        ./UnitTesting/core_Jupyter_notebook_testsuite_GiRonly.sh

  UnitTestdevSymPy:

    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8.12", "3.10", "3.11"]  # Dev SymPy requires Python 3.8+

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install needed ubuntu packages
      run: sudo apt-get install -y texlive-latex-base colordiff pandoc ffmpeg
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install --upgrade nbconvert
        python -m pip install --upgrade git+https://github.com/sympy/sympy/
        python -m pip install testfixtures mpmath jupyter matplotlib scipy nrpylatex
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: UnitTests
      run: |
        ./UnitTesting/run_NRPy_UnitTests.sh python3
