name: MacOS 12

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  UnitTestlatestSymPy:

    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7.15", "3.8.14", "3.10.8", "3.11.0"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install --upgrade nbconvert
        python -m pip install testfixtures sympy mpmath jupyter matplotlib scipy nrpylatex clang_format
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: UnitTests
      run: |
        ./UnitTesting/run_NRPy_UnitTests.sh python3
  TwoBHsCollideJupyterNotebook:

    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7.15", "3.8.14", "3.10.8", "3.11.0"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Brew install needed TeX packages (for pdflatex)
      run: |
        brew install texlive
        brew install ffmpeg colordiff pandoc
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install --upgrade nbconvert
        python -m pip install testfixtures sympy mpmath jupyter matplotlib scipy nrpylatex
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: BSSNTwoBHsCollide
      run: |
        ./run_Jupyter_notebook.sh Tutorial-Start_to_Finish-BSSNCurvilinear-Two_BHs_Collide_new_way.ipynb
